### ISSUE TITLE
Isn't working with the latest updates

### ISSUE THREAD

**Issue by abishekrsrikaanth** [culturekings/shopify-app-auth-laravel#1]
@jonathan-bird Just started working with this packages, but doesn't seem to work with the latest updates from oseintow/laravel-shopify. The latest release of oseintow/laravel-shopify doesn't include the changes for multiple apps

**Comment by jonathan-bird** [comment]
He just needs to release the current dev master branch to a tag and it'll
work. I sent him a message.

**Comment by abishekrsrikaanth** [comment]
Thank you, in the meantime, I am using the forked build till this is solved.
