### ISSUE TITLE
Error on installing app on a store

### ISSUE THREAD

**Issue by abishekrsrikaanth** [culturekings/shopify-app-auth-laravel#10]
I get the following error during the installation of the app on a store

![capto_capture 2017-11-30_11-52-55_am](https://user-images.githubusercontent.com/1639302/33443540-d615d26c-d5c5-11e7-971e-0f424189ceb8.png)

Could you advice what I may be missing. I seem to have correct entries on the tables.

I tried the following on a test route

```
    $shopUrl = "some-name.myshopify.com"; //exists on the db
    $appName = "some-app-name"; //exists on the db

    $user = \CultureKings\ShopifyAuth\Models\ShopifyUser::where('shop_url', $shopUrl)->whereHas('shopifyAppUsers', function ($query) use ($appName) {
        $query->whereShopifyAppName($appName);
    })->get();

    dd($user->shopifyAppUsers->count());
```

![capto_capture 2017-11-30_11-56-27_am](https://user-images.githubusercontent.com/1639302/33443556-e0bdf438-d5c5-11e7-93c9-86bdb0a2817d.png)

**Comment by hktech-meatti** [comment]
$user should be collection instead of ShopifyUser , change ->get() to ->first() , and remove 
isEmpty() checking
