### ISSUE TITLE
Clarity on package setup

### ISSUE THREAD

**Issue by abishekrsrikaanth** [culturekings/shopify-app-auth-laravel#2]
So far, it has been quite easy to set the package, but there are a few minor hiccups. I understand this package is quite new and will have more documentation in the future, could you please provide some clarity.

1. How to set the package to use for multiple apps within the same repository
2. There is a success page, which is kinda the default the page that it redirects to on successful installation of the app and also when the user opens an app that was already installed. Is there a way to open a different page instead of opening the success page when the app is opened.
3. Based on the `Usage` section (https://github.com/culturekings/shopify-app-auth-laravel#usage), are these variables always accessible on the views or should I use it similar to how it is implemented in https://github.com/culturekings/shopify-app-auth-laravel/blob/master/src/Http/Controllers/AuthController.php#L32

**Comment by jonathan-bird** [comment]
Updated readme & code. Should be all working now.

1. That's what app_name is for in the routes etc, multiple apps.
2. Not currently. You can set up a redirect on that view if you like so the user never sees the view when it loads, however at the moment each app must have an install success page.
3. I've beefed out the usage section. Use appName variable in the route to find secret and key in the config file to use for api call.
