### ISSUE TITLE
HMAC validation for request

### ISSUE THREAD

**Issue by abishekrsrikaanth** [culturekings/shopify-app-auth-laravel#4]
Is there a way to validate HMAC validations to validate if the request is coming from Shopify as mentioned in section [Verify the request](https://help.shopify.com/api/tutorials/building-public-app) or is this out of the package scope?

**Comment by jonathan-bird** [comment]
It does that already within the middleware. If it has a HMAC set, it
verifies it and fails if it doesn't check out.

**Comment by abishekrsrikaanth** [comment]
👍  That was fast

**Comment by abishekrsrikaanth** [comment]
The HMAC validation seems to work without sending HMAC on the request. 
I have an ajax call, the route for which is wrapped with middleware (https://github.com/culturekings/shopify-app-auth-laravel#auth-middleware), but I don't get an error when the HMAC is not specified and nothing gets logged as well from https://github.com/culturekings/shopify-app-auth-laravel/blob/master/src/Http/Middleware/ShopifyAuthCheck.php#L57

**Comment by jonathan-bird** [comment]
Yes, so you can click through the app when in the iframe as it doesn't send the hmac query when that happens. Only requests from shopify send hmac. As soon as you have internal links, it doesnt send it
