### ISSUE TITLE
Checking if it is an existing or new app installation

### ISSUE THREAD

**Issue by abishekrsrikaanth** [culturekings/shopify-app-auth-laravel#5]
Since the only entry point from the config is the `install-success` page, and this is the page that is always loaded everytime the app is opened, is there a good way to check if this is a new installation or an existing installation.

**Comment by jonathan-bird** [comment]
This page should not be loaded everytime you open the app. That's what the
dashboard is for.

**Comment by abishekrsrikaanth** [comment]
Not sure I understand this clearly. I see in the docs that the routes are being set up with the middleware but what or how does one go about redirecting to the `dashboard` page? Is this built in or does that need to be handled manually?

**Comment by jonathan-bird** [comment]
This can be done from your install success page.

Thanks

**Comment by abishekrsrikaanth** [comment]
Could you give me an example of how I can do that from the install success page?

**Comment by jonathan-bird** [comment]
v2 allows you to customise the view for install success page. Change it to dashboard if you want. See docs for updated shopify-auth.php config
